[workspace]
authors = ["Chris Choi <chutsu@gmail.com>"]
channels = ["conda-forge"]
name = "xyz-python"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.4.2,<3"
scipy = ">=1.17.1,<2"
matplotlib = ">=3.10.8,<4"
pyyaml = ">=6.0.3,<7"
sphinx = ">=8.2.3,<9"
sphinx-rtd-theme = ">=3.1.0,<4"
py-opencv = ">=4.13.0,<5"
pytest = ">=9.0.2,<10"
pandas = ">=3.0.1,<4"
