name: ci
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@master

    - name: Load cached Docker image
        id: load-cache
        uses: actions/cache@v4
        with:
          path: /tmp/.docker-cache
          key: docker-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-${{ runner.os }}-

    - name: Load Docker image from cache if available
      run: |
        if [ -f /tmp/.docker-cache/image.tar ]; then
          docker load -i /tmp/.docker-cache/image.tar
        fi

    - name: Build Docker image
      run: |
        make docker

    - name: Save Docker image to cache
      run: |
        mkdir -p /tmp/.docker-cache
        docker save myapp:latest -o /tmp/.docker-cache/image.tar

    - name: Run unit tests inside Docker
      run: |
        docker run --rm xyz:latest bash -c "make ci"
