name: ci
on: [push]
jobs:
  run_ci:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: make third_party

    - name: Build libproto
      run: make libxyz

    - name: Run CI tests
      run: make ci
